language: objective-c
osx_image: xcode11

install:
  - bundle install
  - gem install xcpretty-travis-formatter

script:
  - set -eo pipefail
  - bundle exec pod repo update
  - bundle exec pod lib lint --allow-warnings
  - Pods/SwiftLint/swiftlint --strict
  - xcodebuild test -workspace ModernAVPlayer.xcworkspace -scheme ModernAVPlayer-Example -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty -f `xcpretty-travis-formatter`
